SET client_min_messages TO WARNING;

\ir 'env.sql'

BEGIN;

\echo `# Configure database privileges`

REVOKE ALL ON LANGUAGE plpgsql FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA information_schema FROM PUBLIC;

REVOKE ALL ON pg_catalog.pg_auth_members FROM PUBLIC;
REVOKE ALL ON pg_catalog.pg_group FROM PUBLIC;
REVOKE ALL ON pg_catalog.pg_roles FROM PUBLIC;
REVOKE ALL ON pg_catalog.pg_user FROM PUBLIC;
REVOKE ALL ON pg_catalog.pg_user_mappings FROM PUBLIC;

CREATE USER editor WITH ENCRYPTED PASSWORD 'md5e1cd61afab63c461ab483e94c917a39f';

GRANT ALL ON SCHEMA public TO editor;
GRANT ALL ON SCHEMA information_schema TO editor;

GRANT SELECT ON pg_catalog.pg_roles TO editor;
GRANT SELECT ON pg_catalog.pg_user TO editor;

ALTER DEFAULT PRIVILEGES REVOKE ALL ON ROUTINES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SCHEMAS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TYPES FROM PUBLIC;

COMMIT;